print('Girar 
print('Girar 90º hacia la derecha')
print('Girar 90º hacia la derecha')
print('Avanza exactamente dos casillas hacia el frente')
print('Girar 90º hacia la derecha')
print('Avanza exactamente dos casillas hacia el frente')
print('Retrocede una casilla hacia la dirección opuesta del frente')
print('Avanza exactamente dos casillas hacia el frente')
print('Girar 90º hacia la derecha')
print('Retrocede una casilla hacia la dirección opuesta del frente')
print('Avanza exactamente dos casillas hacia el frente')
print('Girar 90º hacia la derecha')
print('Girar 90º hacia la derecha')
print('Girar 90º hacia la derecha')
print('Avanza exactamente dos casillas hacia el frente')
print('Girar 90º hacia la derecha')
print('Retrocede una casilla hacia la dirección opuesta del frente')
print('Girar 90º hacia la derecha')
print('Retrocede una casilla hacia la dirección opuesta del frente')
print('Gira 90º hacia la derecha')
print('Avanza exactamente dos casillas hacia el frente')
print('Gira 90º hacia la derecha')
print('Retrocede una casilla hacia la dirección opuesta del frente')
print('Avanza exactamente dos casillas hacia el frente')
print('Gira 90º hacia la derecha')
print('Gira 90º hacia la derecha')
print('Gira 90º hacia la derecha')
print('Avanza exactamente dos casillas hacia el frente')
print('Retrocede una casilla hacia la dirección opuesta del frente')
print('Avanza exactamente dos casillas hacia el frente')
Final= 'Mision concluida'
